# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio_description', models.CharField(blank=True, max_length=300, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Twitter Profile',
            },
        ),
    ]
